
#
#  This is a cool Quarkus project using version: 3.8
#
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test2
  description: A cool quarkus app
  annotations:
    argocd/app-name: test2-bootstrap
    backstage.io/kubernetes-id: test2
    # It must be commented otherwise we cannot see the Tekton pipelines resources
    # backstage.io/kubernetes-namespace: qshift
    backstage.io/source-location: url:https://github.com/ch007m/test2
    # The janus-idp.io/tekton allows to set the boolean value: isTektonCIAvailable which is used within the UI to enable/disable the TektonCIComponent
    janus-idp.io/tekton: test2
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ch007m/
    # See: topology annotation: https://github.com/janus-idp/backstage-plugins/tree/main/plugins/topology
    app.kubernetes.io/name: quarkus
    app.quarkus.io/quarkus-version: "3.8"
  tags:
    - java
    - quarkus
  links:
    - url: https://test2-qshift.apps.qshift.snowdrop.dev/
      title: Quarkus application url
      icon: web
spec:
  type: service
  lifecycle: production
  owner: user:guest
